### ISSUE TITLE
Link both bigtable and storage clients results in a crash.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1087]
With Bazel, linking both the bigtable client and the storage client, results in a crash. I (@coryan) suspect it is the versions of OpenSSL: gRPC links BoringSSL, libcurl links the native OpenSSL.

/cc: @drethage

**Comment by coryan** [comment]
Compiled with Bazel the program crashes:

```
[Thread 0x7f2426c25700 (LWP 250742) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007f24321d9afc in SSL_ctrl () from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
(gdb) where
#0  0x00007f24321d9afc in SSL_ctrl () from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
#1  0x00007f2432468d26 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#2  0x00007f243246bb2f in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#3  0x00007f243246c97a in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#4  0x00007f2432418cf2 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#5  0x00007f243241a5bb in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#6  0x00007f2432425846 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#7  0x00007f243243b406 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#8  0x00007f243243c383 in curl_multi_perform () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#9  0x00007f2432432415 in curl_easy_perform () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#10 0x000056065cbb05fc in google::cloud::storage::v0::internal::CurlHandle::EasyPerform (this=0x56065dde51b0) at ./google/cloud/storage/internal/curl_handle.h:145
#11 0x000056065cbafbbf in google::cloud::storage::v0::internal::CurlRequest::MakeRequest (this=0x56065dde50e8) at google/cloud/storage/internal/curl_request.cc:26
#12 0x000056065cb9fcaa in google::cloud::storage::v0::internal::AuthorizedUserCredentials<google::cloud::storage::v0::internal::CurlRequestBuilder>::Refresh (this=0x56065dde50e0)
```

I think this confirms my suspicion that the multiple SSL libraries is not a good idea.
