### ISSUE TITLE
row_reader_test and terminate_handler_test reliably crash

### ISSUE THREAD

**Issue by remyabel** [GoogleCloudPlatform/google-cloud-cpp#1729]
### Does this issue affect the `google-cloud-cpp` project?

Yes.

### What component of `google-cloud-cpp` is this related to?

- Cloud Bigtable.

### What version of `google-cloud-cpp` are you using?

b9f13771d418cfdfe2d484c79e83673adf364a2f

### What compiler and version are you using?

```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.2.1 20181215 (Red Hat 8.2.1-6) (GCC)
```

### What operating system and version are you using?

Fedora 29

### What were you trying to do?

Run `ctest`

### What did you expect to see?

No crashes. It doesn't affect the tests, but it's annoying since it fills up my abrt folder/notifications

### What did you see instead?

Tests finish successfully, but two tests (see title) always crash after they finish

### Anything else you would like us to know?

Here's a backtrace for `row_reader_test`:

```
#0  0x00007fea50a2b53f in raise () from /lib64/libc.so.6
#1  0x00007fea50a15895 in abort () from /lib64/libc.so.6
#2  0x00007fea50deae9b in ?? () from /lib64/libstdc++.so.6
#3  0x00007fea50df12fc in ?? () from /lib64/libstdc++.so.6
#4  0x00007fea50df0319 in ?? () from /lib64/libstdc++.so.6
#5  0x00007fea50df0cc8 in __gxx_personality_v0 () from /lib64/libstdc++.so.6
#6  0x00007fea50bca273 in ?? () from /lib64/libgcc_s.so.1
#7  0x00007fea50bca7e1 in _Unwind_RaiseException () from /lib64/libgcc_s.so.1
#8  0x00007fea50df15ab in __cxa_throw () from /lib64/libstdc++.so.6
#9  0x00000000004e02a9 in void (anonymous namespace)::RaiseException<std::runtime_error>(char const*) ()
#10 0x00000000004e00ff in google::cloud::v0::internal::RaiseRuntimeError(char const*) ()
#11 0x00000000004927d5 in google::cloud::bigtable::v0::RowReader::~RowReader()
    ()
#12 0x000000000043d7da in std::default_delete<google::cloud::bigtable::v0::RowReader>::operator()(google::cloud::bigtable::v0::RowReader*) const ()
#13 0x00000000004377b1 in std::unique_ptr<google::cloud::bigtable::v0::RowReader, std::default_delete<google::cloud::bigtable::v0::RowReader> >::reset(google::cloud::bigtable::v0::RowReader*) ()
#14 0x00000000004275b9 in RowReaderTest_NoExceptionDestructorWillRaiseIfErrorNotRetrived_Test::TestBody() ()
#15 0x00000000006ea3ca in void testing::internal::HandleExceptionsInMethodIfSupp--T--Type <RE--Type <-----Type <RET> for more, q to quit, c to continue without paging--
orted<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#16 0x00000000006e25c9 in testing::Test::Run() [clone .part.610] ()
#17 0x00000000006e2825 in testing::TestInfo::Run() [clone .part.611] ()
#18 0x00000000006e29ab in testing::TestCase::Run() [clone .part.612] ()
#19 0x00000000006e2fbb in testing::internal::UnitTestImpl::RunAllTests() ()
#20 0x00000000006ea88a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#21 0x00000000006e3126 in testing::UnitTest::Run() ()
#22 0x00000000004dd8a0 in RUN_ALL_TESTS() ()
#23 0x00000000004dd839 in main ()
```

*N.B.*: doesn't seem to happen if I run the test directly.

**Comment by remyabel** [comment]
Didn't realize that those were death tests.
